### PR TITLE
Add list

### PR DESCRIPTION
**Pull request by hbtpoprock**
this is a pull request testing

### CODE REVIEW

**Comment by oaksupanat** [comment]
@hbtpoprock  I said please add me as a Reviewer of the PRs. please try doing it.

**Review by oaksupanat — COMMENTED** [review]
Good

**Comment by oaksupanat** [comment]
@hbtpoprock try merging this PR and see how it's gonna be.

**Comment by bazlance** [comment]
@OakSupanat ok

**Comment by bazlance** [comment]
@OakSupanat All the pull requests were closed right after merging #2 to its `master`. Does it mean that we can make pull requests as many as we want at the same time, BUT once it merged all the requests would be closed? Since the other pull request, #1, was closed as well, and I have no any fucking idea :(

**Comment by oaksupanat** [comment]
@hbtpoprock The PR will be automatically closed (by GitHub) after it is merged.
And when you merge PR#1 into the master branch. The next PR#2 you want to merge must have no conflict with the recently updated master branch, if there're some conflicts, you have to pull the master branch into your branch of PR#2 then fix the conflict before try to merge PR#2 into master branch.

**Pull request merged**
